# Generated by Django 5.2.7 on 2026-01-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="rating",
            field=models.IntegerField(default=1000, verbose_name="레이팅"),
        ),
    ]
