# Generated by Django 5.2.7 on 2026-02-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_rating_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="chat_banned_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="채팅 금지 만료"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="is_permanently_banned",
            field=models.BooleanField(default=False, verbose_name="영구 정지"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="suspended_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="계정 정지 만료"
            ),
        ),
    ]
