# Generated by Django 5.2.7 on 2026-02-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_avatar',
            field=models.CharField(choices=[('green', '초록 (오목판)'), ('blue', '파랑'), ('red', '빨강'), ('purple', '보라'), ('yellow', '노랑'), ('pink', '핑크'), ('cyan', '하늘'), ('gray', '회색')], default='green', max_length=20, verbose_name='기본 아바타 색상'),
        ),
    ]
