# Generated by Django 5.2.6 on 2025-09-30 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('turn', models.CharField(default='black', max_length=5)),
                ('winner', models.CharField(blank=True, max_length=5, null=True)),
                ('board', models.CharField(default='.................................................................................................................................................................................................................................', max_length=225)),
                ('black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_black', to=settings.AUTH_USER_MODEL)),
                ('white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='games.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('game', 'x', 'y')},
            },
        ),
    ]
