# Generated by Django 5.2.7 on 2025-12-05 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "game_id",
                    models.IntegerField(help_text="원본 Game ID (삭제된 게임 참조용)"),
                ),
                ("winner", models.CharField(max_length=5)),
                ("created_at", models.DateTimeField(help_text="게임 시작 시간")),
                (
                    "finished_at",
                    models.DateTimeField(auto_now_add=True, help_text="게임 종료 시간"),
                ),
                ("total_moves", models.IntegerField(help_text="총 수 개수")),
                (
                    "black",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_black",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "white",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="history_as_white",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-finished_at"],
                "indexes": [
                    models.Index(
                        fields=["black", "-finished_at"],
                        name="games_gameh_black_i_43b119_idx",
                    ),
                    models.Index(
                        fields=["white", "-finished_at"],
                        name="games_gameh_white_i_bd15c1_idx",
                    ),
                ],
            },
        ),
    ]
