# Generated by Django 5.2.7 on 2025-12-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_black_time_remaining_game_last_move_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_ready',
            field=models.BooleanField(default=False, help_text='흑 플레이어 준비 완료'),
        ),
        migrations.AddField(
            model_name='game',
            name='game_started',
            field=models.BooleanField(default=False, help_text='게임 시작 여부'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_ready',
            field=models.BooleanField(default=False, help_text='백 플레이어 준비 완료'),
        ),
    ]
