# Generated by Django 5.2.7 on 2025-12-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='rematch_black',
            field=models.BooleanField(default=False, help_text='흑 플레이어 리매치 요청'),
        ),
        migrations.AddField(
            model_name='game',
            name='rematch_white',
            field=models.BooleanField(default=False, help_text='백 플레이어 리매치 요청'),
        ),
    ]
