# Generated by Django 5.2.7 on 2026-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0006_game_rematch_black_game_rematch_white"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="방 비밀번호 (선택사항)",
                max_length=128,
                null=True,
            ),
        ),
    ]
