# Generated by Django 5.2.7 on 2026-01-10 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0007_game_password"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="메시지 내용")),
                ("is_read", models.BooleanField(default=False, help_text="읽음 여부")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="메시지 생성 시간"
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="메시지 수신자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_direct_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="메시지 발신자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_direct_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="games_direc_recipie_2d6ce2_idx",
                    ),
                    models.Index(
                        fields=["sender", "-created_at"],
                        name="games_direc_sender__142d46_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="친구 관계 생성 시간"
                    ),
                ),
                (
                    "friend",
                    models.ForeignKey(
                        help_text="친구",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="befriended_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="friends",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="games_frien_user_id_df931b_idx",
                    )
                ],
                "unique_together": {("user", "friend")},
            },
        ),
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="요청 생성 시간"),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        help_text="요청 보낸 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        help_text="요청 받은 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_friend_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["to_user", "-created_at"],
                        name="games_frien_to_user_81d08c_idx",
                    )
                ],
                "unique_together": {("from_user", "to_user")},
            },
        ),
    ]
