# Generated by Django 5.2.7 on 2026-01-27 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0008_directmessage_friend_friendrequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LobbyMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(help_text="메시지 내용")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="메시지 생성 시간"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="메시지 작성자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lobby_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="games_lobby_created_f8fba2_idx"
                    )
                ],
            },
        ),
    ]
