# Generated by Django 5.2.7 on 2026-02-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0009_lobbymessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("user", "유저 신고"),
                            ("chat", "채팅 신고"),
                            ("game", "게임 신고"),
                        ],
                        max_length=10,
                        verbose_name="신고 유형",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "욕설/비하"),
                            ("spam", "도배/스팸"),
                            ("cheat", "핵/치팅 의심"),
                            ("stalling", "고의 시간끌기"),
                            ("inappropriate", "부적절한 행동"),
                            ("other", "기타"),
                        ],
                        max_length=20,
                        verbose_name="신고 사유",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="상세 설명")),
                ("evidence", models.TextField(blank=True, verbose_name="증거")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("reviewed", "처리완료"),
                            ("dismissed", "기각"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="처리 상태",
                    ),
                ),
                (
                    "admin_note",
                    models.TextField(blank=True, verbose_name="관리자 메모"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신고 시간"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="처리 시간"
                    ),
                ),
                (
                    "reported_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="피신고자",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_filed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신고자",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리 관리자",
                    ),
                ),
            ],
            options={
                "verbose_name": "신고",
                "verbose_name_plural": "신고",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Sanction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sanction_type",
                    models.CharField(
                        choices=[
                            ("warning", "경고"),
                            ("chat_ban", "채팅 금지"),
                            ("suspend", "계정 정지"),
                            ("permanent_ban", "영구 정지"),
                        ],
                        max_length=20,
                        verbose_name="제재 유형",
                    ),
                ),
                ("reason", models.TextField(verbose_name="제재 사유")),
                (
                    "duration_days",
                    models.IntegerField(blank=True, null=True, verbose_name="기간(일)"),
                ),
                (
                    "starts_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="시작 시간"),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료 시간"
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions_issued",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="처리 관리자",
                    ),
                ),
                (
                    "related_report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sanctions",
                        to="games.report",
                        verbose_name="관련 신고",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanctions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="제재 대상",
                    ),
                ),
            ],
            options={
                "verbose_name": "제재",
                "verbose_name_plural": "제재",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"], name="games_repor_status_599af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reported_user", "-created_at"],
                name="games_repor_reporte_2ce258_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sanction",
            index=models.Index(
                fields=["user", "-starts_at"], name="games_sanct_user_id_28578a_idx"
            ),
        ),
    ]
